#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. /usr/not-backed-up/cfd/job/functions/RunFunctions               

# Make dummy 0 directory
cp -r 0.orig 0

runApplication decomposePar

runParallel potentialFoam -initialiseUBCs

runParallel `getApplication`

#------------------------------------------------------------------------------
