#!/bin/sh

# Source tutorial run functions
. /nobackup/scrh/cfd/job/functions/RunFunctions   

# Set-up the LES case
cp ../lesFiles/fvS* ../lesFiles/controlDict system/
cp ../lesFiles/turbulenceProperties constant/

ls -d processor* | xargs -I {} rm -rf ./{}/0 $1
ls -d processor* | xargs -I {} mv ./{}/5 ./{}/0 $1
ls -d processor* | xargs -I {} rm -rf ./{}/0/uniform $1

mpirun -np 72 pimpleFoam -parallel >> log

